/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    packages: Package;
    inquiry: Inquiry;
    "fixed-packages": FixedPackage;
    "last-minute-packages": LastMinutePackage;
    contact: Contact;
    categories: Category;
    locations: Location;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    inquiry: InquirySelect<false> | InquirySelect<true>;
    "fixed-packages": FixedPackagesSelect<false> | FixedPackagesSelect<true>;
    "last-minute-packages": LastMinutePackagesSelect<false> | LastMinutePackagesSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences": PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations": PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    home: Home;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  user: User & {
    collection: "users";
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: "admin" | "editor";
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  destination?: string | null;
  title?: string | null;
  package?: string | null;
  cost?: number | null;
  image?: (number | null) | Media;
  is_popular?: boolean | null;
  popular_order?: number | null;
  order?: number | null;
  type?: ("domestic" | "international" | "cruise") | null;
  category?: (number | Category)[] | null;
  location?: (number | null) | Location;
  gallery?: (number | Media)[] | null;
  overview?: string | null;
  highlights?: {
    chips?:
      | {
          chip?: string | null;
          id?: string | null;
        }[]
      | null;
    pointers?:
      | {
          pointer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  day_breakup?: {
    days?:
      | {
          title?: string | null;
          break_up?:
            | {
                title?: string | null;
                subtitle?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  accomodations?: {
    locations?:
      | {
          image?: (number | null) | Media;
          name?: string | null;
          location?: string | null;
          type?: string | null;
          whats_included?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry".
 */
export interface Inquiry {
  id: number;
  name?: string | null;
  mobile?: string | null;
  email?: string | null;
  travellers?: string | null;
  destination?: string | null;
  type?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixed-packages".
 */
export interface FixedPackage {
  id: number;
  destination?: string | null;
  package?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  cost?: number | null;
  image?: (number | null) | Media;
  order?: number | null;
  category?: "Group" | null;
  gallery?: (number | Media)[] | null;
  overview?: string | null;
  highlights?: {
    chips?:
      | {
          chip?: string | null;
          id?: string | null;
        }[]
      | null;
    pointers?:
      | {
          pointer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  day_breakup?: {
    days?:
      | {
          title?: string | null;
          date?: string | null;
          break_up?:
            | {
                title?: string | null;
                subtitle?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  accomodations?: {
    locations?:
      | {
          image?: (number | null) | Media;
          name?: string | null;
          location?: string | null;
          type?: string | null;
          whats_included?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "last-minute-packages".
 */
export interface LastMinutePackage {
  id: number;
  destination?: string | null;
  package?: string | null;
  discount?: number | null;
  order?: number | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  cost?: number | null;
  image?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  overview?: string | null;
  highlights?: {
    chips?:
      | {
          chip?: string | null;
          id?: string | null;
        }[]
      | null;
    pointers?:
      | {
          pointer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  day_breakup?: {
    days?:
      | {
          title?: string | null;
          break_up?:
            | {
                title?: string | null;
                subtitle?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  accomodations?: {
    locations?:
      | {
          image?: (number | null) | Media;
          name?: string | null;
          location?: string | null;
          type?: string | null;
          whats_included?: string | null;
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  name?: string | null;
  mobile?: string | null;
  email?: string | null;
  destination?: string | null;
  ideas?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "packages";
        value: number | Package;
      } | null)
    | ({
        relationTo: "inquiry";
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: "fixed-packages";
        value: number | FixedPackage;
      } | null)
    | ({
        relationTo: "last-minute-packages";
        value: number | LastMinutePackage;
      } | null)
    | ({
        relationTo: "contact";
        value: number | Contact;
      } | null)
    | ({
        relationTo: "categories";
        value: number | Category;
      } | null)
    | ({
        relationTo: "locations";
        value: number | Location;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  destination?: T;
  title?: T;
  package?: T;
  cost?: T;
  image?: T;
  is_popular?: T;
  popular_order?: T;
  order?: T;
  type?: T;
  category?: T;
  location?: T;
  gallery?: T;
  overview?: T;
  highlights?:
    | T
    | {
        chips?:
          | T
          | {
              chip?: T;
              id?: T;
            };
        pointers?:
          | T
          | {
              pointer?: T;
              id?: T;
            };
      };
  day_breakup?:
    | T
    | {
        days?:
          | T
          | {
              title?: T;
              break_up?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  accomodations?:
    | T
    | {
        locations?:
          | T
          | {
              image?: T;
              name?: T;
              location?: T;
              type?: T;
              whats_included?: T;
              link?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry_select".
 */
export interface InquirySelect<T extends boolean = true> {
  name?: T;
  mobile?: T;
  email?: T;
  travellers?: T;
  destination?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fixed-packages_select".
 */
export interface FixedPackagesSelect<T extends boolean = true> {
  destination?: T;
  package?: T;
  start_date?: T;
  end_date?: T;
  cost?: T;
  image?: T;
  order?: T;
  category?: T;
  gallery?: T;
  overview?: T;
  highlights?:
    | T
    | {
        chips?:
          | T
          | {
              chip?: T;
              id?: T;
            };
        pointers?:
          | T
          | {
              pointer?: T;
              id?: T;
            };
      };
  day_breakup?:
    | T
    | {
        days?:
          | T
          | {
              title?: T;
              date?: T;
              break_up?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  accomodations?:
    | T
    | {
        locations?:
          | T
          | {
              image?: T;
              name?: T;
              location?: T;
              type?: T;
              whats_included?: T;
              link?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "last-minute-packages_select".
 */
export interface LastMinutePackagesSelect<T extends boolean = true> {
  destination?: T;
  package?: T;
  discount?: T;
  order?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  cost?: T;
  image?: T;
  gallery?: T;
  overview?: T;
  highlights?:
    | T
    | {
        chips?:
          | T
          | {
              chip?: T;
              id?: T;
            };
        pointers?:
          | T
          | {
              pointer?: T;
              id?: T;
            };
      };
  day_breakup?:
    | T
    | {
        days?:
          | T
          | {
              title?: T;
              break_up?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  accomodations?:
    | T
    | {
        locations?:
          | T
          | {
              image?: T;
              name?: T;
              location?: T;
              type?: T;
              whats_included?: T;
              link?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  name?: T;
  mobile?: T;
  email?: T;
  destination?: T;
  ideas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero_Packages?: (number | Package)[] | null;
  last_minute_date?: {
    show_last_minute_packages?: boolean | null;
    start_date?: string | null;
    end_date?: string | null;
  };
  show_fixed_departures_packages?: boolean | null;
  testimonials_home?:
    | {
        name?: string | null;
        review?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  testimonials_domestic?:
    | {
        name?: string | null;
        review?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  testimonials_international?:
    | {
        name?: string | null;
        review?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  testimonials_cruise?:
    | {
        name?: string | null;
        review?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero_Packages?: T;
  last_minute_date?:
    | T
    | {
        show_last_minute_packages?: T;
        start_date?: T;
        end_date?: T;
      };
  show_fixed_departures_packages?: T;
  testimonials_home?:
    | T
    | {
        name?: T;
        review?: T;
        image?: T;
        id?: T;
      };
  testimonials_domestic?:
    | T
    | {
        name?: T;
        review?: T;
        image?: T;
        id?: T;
      };
  testimonials_international?:
    | T
    | {
        name?: T;
        review?: T;
        image?: T;
        id?: T;
      };
  testimonials_cruise?:
    | T
    | {
        name?: T;
        review?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
